import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private currentLangSubject = new BehaviorSubject<'zh' | 'en'>('zh');
  public currentLang$ = this.currentLangSubject.asObservable();

  private translations = {
    zh: {
      nav: {
        home: '首页',
        search: '搜索',
        publish: '发布',
        msg: '消息',
        me: '我的',
      },
      tab1: {
        btnText: '中文',
        modalTitle: '提示 / Alert',
        modalBody: '您确定要切换语言吗？<br><span class="sub-text">Are you sure you want to switch language?</span>',
        cancel: '取消 / Cancel',
        confirm: '确定 / OK',
        searchPlaceholder: '点击搜索',
        requestTitle: '求助',
        helpTitle: '帮助',
        noEvent: '还没有求助事件',
        noHelp: '还没有帮助事件',
        more: '更多',
        unknownDistance: '未知距离',
      },
      tab2: {
        title: '搜索',
        searchPlaceholder: '点击搜索',
        noResults: '暂无搜索结果',
        filterAll: '全部',
        filterRequest: '求助',
        filterHelp: '帮助',
        unknownDistance: '未知距离',
        loadFailed: 'Tab2 加载失败',
      },
      tab3: {
        title: '消息',
        loginRequired: '您好！请登录',
        loginRequiredSub: '欢迎使用 HelpMe',
        loginHint: '登录后查看消息列表',
        loginBtn: '立即登录',
        registerBtn: '注册账号',
        notification: '通知',
        systemNotification: '系统通知',
        noNewNotification: '暂无新通知',
        noMessage: '暂无消息',
        loginToast: '请您登录或注册',
        loadRoomsFailed: '加载聊天列表失败',
        unknownUser: '用户',
      },
      tab4: {
        title: '个人中心',
        welcome: '欢迎使用 HelpMe',
        loginHint: '登录后查看个人中心',
        loginBtn: '立即登录',
        registerBtn: '注册账号',
        locationNotSet: '未设置位置',
        introDefault: '个人的介绍，等待以后再来探索吧！',
        buyerRating: '买家评分',
        serviceRating: '服务评分',
        orderCount: '服务单数',
        editProfile: '编辑资料',
        logout: '登出',
        follow: '关注',
        favorite: '收藏',
        view: '浏览',
        tabPublished: '我发布的',
        tabInProgress: '正进行的',
        tabCompleted: '已完成',
        tabReview: '评价',
        publishTime: '发布时间',
        delete: '删除',
        edit: '编辑',
        viewDetails: '详情',
        review: '评价',
        deleting: '删除中...',
        noTasks: '暂无相关任务',
        deleteConfirmTitle: '确认删除',
        deleteConfirmMsg: '删除后不可恢复，是否继续？',
        cancel: '取消',
        confirm: '确定',
        editEventTitle: '编辑事件',
        close: '关闭',
        titleLabel: '标题',
        titlePlaceholder: '简明描述（如：上门电脑维修）',
        typeLabel: '类型',
        typePlaceholder: '请选择事件类型',
        typeRequest: '求助',
        typeHelp: '帮助',
        categoryLabel: '类别',
        categoryPlaceholder: '如：电脑维修',
        locationLabel: '位置',
        locationPlaceholder: '详细地址',
        priceLabel: '价格 (¥)',
        pricePlaceholder: '0 表示无偿帮助',
        detailsLabel: '详细描述',
        detailsPlaceholder: '补充说明需求/服务内容',
        editPhotoLabel: '编辑图片（可选）',
        uploadPhoto: '点击上传照片',
        uploadHint: '最多可上传 5 张照片，支持 JPG/PNG',
        save: '保存',
        saving: '保存中...',
        editProfileTitle: '编辑个人资料',
        changeAvatar: '更换头像',
        uploadAvatar: '上传头像',
        avatarHint: '支持jpg/png，最大5MB',
        userNameLabel: '用户名',
        userNamePlaceholder: '请输入用户名（2-20个字符）',
        realNameLabel: '真实姓名',
        realNamePlaceholder: '请输入真实姓名（2-20个字符）',
        idCardLabel: '身份证号',
        idCardPlaceholder: '请输入18位身份证号',
        locationLabelProfile: '所在地',
        locationPlaceholderProfile: '例如：广西柳州',
        birthDateLabel: '出生日期',
        introLabel: '个人介绍',
        introPlaceholder: '简单介绍一下自己吧（选填，最多200字）',
        requiredHint: '* 标记为必填项',
        verified: '已认证',
        rejected: '被驳回',
        pending: '待审核',
        notVerified: '未认证',
        statusPublished: '已发布',
        statusInProgress: '进行中',
        statusCompleted: '已完成',
        statusPendingReview: '待评价',
        statusUnknown: '未知',
        logoutSuccess: '已成功登出',
        deleteSuccess: '删除成功',
        saveSuccess: '保存成功',
        notLoggedIn: '未登录，无法操作',
        loginExpired: '未登录或登录已过期',
        networkError: '网络错误，稍后重试',
        pleaseCompleteRequired: '请完善必填项后再提交',
        titleRequired: '标题必填',
        categoryRequired: '类别必填',
        locationRequired: '位置必填',
        detailsRequired: '详细描述必填',
        priceInvalid: '价格需在 0 ~ 1000000 之间',
        // 子组件通用
        all: '全部',
        pendingConfirm: '待确认',
        confirmComplete: '确认完成',
        goReview: '去评价',
        viewReview: '查看评价',
        orderDetail: '订单详情',
        eventDetail: '事件详情',
        eventNo: '事件号：',
        noEvents: '暂无事件',
        noOrders: '暂无订单',
        eventLoading: '事件加载中...',
        orderLoading: '订单加载中...',
        linkedOrderBlockDelete: '有关联订单，禁止删除',
        // 我的事件面板
        myEvents: '我的事件',
        // 我的订单面板
        myOrders: '我的订单',
        // 订单详情弹窗
        orderInfo: '订单信息',
        orderId: '订单号：',
        orderTime: '下单时间：',
        buyer: '买家',
        seller: '卖家',
        orderStatus: '订单状态：',
        dealPrice: '成交价格：',
        eventInfoOnOrder: '下单时的事件信息',
        categoryColon: '类别：',
        uncategorized: '未分类',
        locationColon: '地点：',
        notFilled: '未填写',
        priceColon: '价格：',
        descriptionColon: '描述：',
        eventPhotos: '事件照片：',
        stopEditOrderInProgress: '订单进行中或待评价时，不允许编辑事件',
        // 评价弹窗
        orderReviewTitle: '订单评价',
        rating: '评分',
        fiveStar: '5 分',
        fourStar: '4 分',
        threeStar: '3 分',
        twoStar: '2 分',
        oneStar: '1 分',
        reviewContent: '评价内容',
        reviewPlaceholder: '写下你的评价',
        submitReview: '提交评价',
        reviewDetailTitle: '订单评价详情',
        loading: '加载中...',
        noReviews: '暂无评价',
        reviewSubmitted: '评价已提交',
        alreadyReviewed: '你已经评价过该订单，请等待对方评价',
        // 订单操作
        confirmOrder: '确认订单',
        cancelOrder: '取消订单',
        confirmCancelMsg: '确定要取消该订单吗？取消后不可恢复。',
        confirmCancel: '确认取消',
        orderConfirmed: '订单已确认',
        orderCompleted: '订单已完成',
        orderCancelled: '订单已取消',
        // 自定义 alert 按钮
        alertCancel: '取消',
        alertConfirm: '确定',
      },
      shared: {
        search: {
          placeholder: '输入需求描述...',
          priceRange: '价格区间',
          locationFilter: '地点筛选',
          reset: '重置',
          noResults: '暂无符合条件的需求',
          priceFilterTitle: '价格筛选',
          close: '关闭',
          minPrice: '最低',
          maxPrice: '最高',
          locationFilterTitle: '输入地点关键词',
          locationLabel: '地点关键词 (匹配地址)',
          locationPlaceholder: '例如: 广科, 001...',
          request: '求助',
          help: '帮助',
        },
        eventCard: {
          eventImage: '事件图片',
          userAvatar: '用户头像',
        },
        eventsPanel: {
          loading: '事件加载中...',
          notFilled: '未填写地点',
          eventNo: '事件号：',
          details: '详情',
          editForbidden: '订单进行中，禁止编辑',
          deleteForbidden: '有关联订单，禁止删除',
          edit: '编辑',
          deleting: '删除中...',
          delete: '删除',
          noEvents: '暂无事件',
        },
        ordersPanel: {
          all: '全部',
          pending: '待确认',
          inProgress: '进行中',
          pendingReview: '待评价',
          completed: '已完成',
          buyer: '买家',
          seller: '卖家',
          orderNo: '订单号：',
          orderDetail: '订单详情',
          eventDetail: '事件详情',
          cancelOrder: '取消订单',
          confirmOrder: '确认订单',
          confirmComplete: '确认完成',
          goReview: '去评价',
          waitReview: '已评价，等待对方',
          viewReview: '查看评价',
          noOrders: '暂无订单',
          loading: '订单加载中...',
        },
        profileCard: {
          realName: '真实姓名：',
          intro: '个人介绍：',
          birthDate: '出生日期：',
        },
      },
      tab5: {
        header: '发布服务',
        hero: '互帮互助一家亲',
        reqTitle: '求助',
        reqDesc: '我有困难时发布',
        helpTitle: '帮助',
        helpDesc: '你要帮助他人时发布',
        authTitle: '认证资格',
        authDesc: '全职 兼职 商家',
        closeHint: '关闭当前页面，返回上一级',
        form: {
          reqHeader: '发布求助',
          helpHeader: '发布帮助',
          authHeader: '认证资格',
          title: '标题',
          category: '类别',
          location: '位置',
          price: '期望价格 (¥)',
          details: '详细描述',
          uploadPhoto: '上传照片（可选）',
          uploadHint: '最多可上传 5 张照片，支持 JPG/PNG',
          uploadIdCard: '身份证照片',
          uploadCert: '职业证书照片（最多可上传 3 张）',
          realName: '真实姓名',
          phone: '手机号',
          idCard: '身份证号',
          area: '所在区域',
          role: '身份类型',
          intro: '个人简介',
          cancel: '取消',
          submit: '提交',
          submitReq: '提交求助',
          submitHelp: '发布帮助',
          submitAuth: '提交认证',
        },
        placeholder: {
          reqTitle: '简明描述你的需求（如：求修电脑）',
          reqCat: '如：电脑维修',
          reqLoc: '详细地址（如：XX校区1栋101室）',
          reqPrice: '0 表示无偿帮助',
          reqDetail: '请说明具体困难、时间要求、紧急程度等',
          helpTitle: '如：提供电脑维修服务',
          helpCat: '如：电脑维修等',
          helpLoc: '如：XX小区',
          helpPrice: '可填小数（如 59.99） 免费则填写0',
          helpDetail: '说明你能提供什么、时间安排、限制条件等',
          realName: '与身份证一致',
          phone: '11位中国大陆手机号',
          idCard: '18位身份证号码',
          area: '如：XX小区',
          intro: '简要介绍你的服务经验或特长（选填）',
        },
        toast: {
          pleaseComplete: '请完善必填项后再提交',
          loginFirst: '请先登录后再发布',
          publishSuccess: '发布成功',
          authSuccess: '认证提交成功，等待审核',
        },
        validation: {
          titleRequired: '标题必填',
          categoryRequired: '类别必填',
          locationRequired: '位置必填',
          detailsRequired: '详细描述必填',
          priceInvalid: '期望价格必填且必须在 0 ~ 1000000 之间',
          serviceAreaRequired: '服务区域必填',
          serviceDetailsRequired: '服务详情必填',
          servicePriceInvalid: '服务价格必填且必须在 0 ~ 1000000 之间',
          realNameRequired: '真实姓名必填',
          idCardInvalid: '身份证号必填且格式正确（18位，末位可为X）',
          areaRequired: '所在区域必填',
          roleRequired: '身份类型必填（只能填 1/2/3）',
          idCardPhotoRequired: '请上传身份证照片（正反面）',
          certPhotoRequired: '请上传职业证书照片',
        },
      },
      login: {
        title: '登录',
        close: '关闭',
        welcome: '欢迎回来',
        hint: '请输入手机号与验证码完成登录',
        phone: '手机号',
        phonePlaceholder: '请输入手机号',
        code: '验证码',
        codePlaceholder: '请输入验证码',
        sendCode: '发送验证码',
        login: '登录',
        tip: '提示：测试手机号为 1380000000X，验证码 1234',
        invalidPhone: '请输入有效的11位手机号',
        verifyFail: '无法验证手机号，请稍后重试',
        notRegistered: '该手机号未注册，请先注册',
        codeSent: '验证码已发送，验证码为1234',
        incomplete: '请完善手机号和验证码',
        loginSuccess: '登录成功，{name}，欢迎您！',
        loginFailFormat: '登录失败：服务器返回格式异常',
        serverUnreachable: '无法连接到服务器（请确认后端已启动）',
      },
      register: {
        title: '注册',
        close: '关闭',
        step1Title: '验证手机号',
        step1Hint: '请输入您的手机号并获取验证码',
        phone: '手机号',
        phonePlaceholder: '请输入手机号',
        code: '验证码',
        codePlaceholder: '请输入验证码',
        sendCode: '发送验证码',
        next: '下一步',
        tip: '提示：测试验证码为 1234',
        step2Title: '完善个人信息',
        step2Hint: '请填写您的基本信息',
        changeAvatar: '更换头像',
        uploadAvatar: '上传头像',
        deleteAvatar: '删除',
        avatarHint: '未上传将使用默认头像，支持jpg/png，最大5MB',
        userName: '用户名 *',
        realName: '真实姓名 *',
        idCard: '身份证号 *',
        location: '所在地 *',
        locationPlaceholder: '请选择地点',
        birthDate: '出生日期 *',
        intro: '个人介绍',
        introPlaceholder: '简单介绍一下自己吧（选填，最多200字）',
        prev: '上一步',
        registering: '注册中...',
        submit: '完成注册',
        requiredHint: '* 标记为必填项',
        // 错误提示
        phoneRequired: '手机号不能为空',
        codeRequired: '验证码不能为空',
        invalidCode: '验证码错误',
        phoneRegistered: '该手机号已被注册',
        pleaseComplete: '请完善必填项',
        registerSuccess: '注册成功',
        registerFail: '注册失败',
        registerFailFormat: '注册失败：服务器返回格式异常',
        serverUnreachable: '无法连接到服务器（请确认后端已启动）',
        usernameExists: '用户名已存在',
      },
      particular: {
        back: '返回',
        home: '主页',
        buyerRating: '买家评分:',
        serviceRating: '服务评分：',
        serviceCount: '服务次数：',
        registerTime: '注册时间：',
        location: '地点：',
        time: '时间：',
        price: '价格：',
        noImage: '暂无任务图片',
        favorite: '收藏',
        placeOrder: '下单',
        cannotOrder: '暂不可下单',
        edit: '编辑',
        chat: '聊一聊',
        editEvent: '编辑事件',
        close: '关闭',
        titleRequired: '标题 *',
        typeRequired: '类型 *',
        request: '求助',
        help: '帮助',
        categoryRequired: '类别 *',
        locationRequired: '位置 *',
        priceLabel: '价格 (¥)',
        detailsRequired: '详细描述 *',
        saving: '保存中...',
        save: '保存修改',
        orderForm: '填写订单信息',
        addressRequired: '详细地址 *',
        extraInfo: '补充信息',
        submitting: '提交中...',
        confirmOrder: '确认下单',
        editSuccess: '修改成功',
        orderSuccess: '下单成功，等待卖家确认',
        networkError: '网络错误，请稍后重试',
        loginFirst: '请先登录',
      },
      search: {
        placeholder: '输入需求描述',
        back: '返回',
        search: '搜索',
        aiAssist: 'AI辅助',
      },
      chatDetail: {
        title: '聊天详情',
        userAvatar: '用户头像',
        me: '我',
        other: '对方',
        inputPlaceholder: '输入消息...',
        send: '发送',
        justNow: '刚刚',
        systemNotification: '系统通知',
        connected: '连接成功！',
      },
      userParticular: {
        title: '用户详情',
        home: '主页',
        address: '地址:',
        buyerRating: '买家评分:',
        serviceRating: '服务评分：',
        serviceCount: '服务次数：',
        intro: '个人介绍:',
        noIntro: '暂无介绍',
        edit: '编辑',
        follow: '关注',
        publishedEvents: '发布的活动',
        review: '评价',
        historyEvents: '历史活动',
        noActiveEvents: '暂无正在进行的活动',
        noReviews: '暂无评价',
        noHistory: '暂无活动动态',
        loginFirst: '请先登录',
        cannotChatSelf: '不能与自己聊天',
        request: '求助',
        help: '帮助',
        enthusiast: '热心用户',
        expert: '服务达人',
        normal: '普通用户',
        published: '发布活动',
        inProgress: '活动进行中',
        completed: '活动完成',
        pendingReview: '待评价',
        activity: '活动',
        noDescription: '暂无描述',
      },
      locationPicker: {
        title: '选择地点',
        confirmLocation: '确定位置',
        searchPlaceholder: '搜索地点',
        search: '搜索',
        nearbyRecommend: '附近推荐',
        km: 'km内',
        m: 'm内',
        nearby: '附近',
        loading: '正在加载...',
        noResult: '没有找到可选地点，请换个关键词',
        searchResult: '搜索结果',
      },
      // 通用
      common: {
        save: '保存',
        cancel: '取消',
        confirm: '确定',
        close: '关闭',
        delete: '删除',
        edit: '编辑',
        loading: '加载中...',
        noData: '暂无数据',
        networkError: '网络错误，请稍后重试',
        loginExpired: '登录已过期，请重新登录',
        loginSuccessNoToken: '登录成功但服务器未返回 token（请检查后端 JWT 登录接口返回）',
        loginFailedFormat: '登录失败：服务器返回格式异常',
        serverUnreachable: '无法连接到服务器（请确认后端已启动）',
        pleaseComplete: '请填写所有必填项',
      },
    },
    en: {
      nav: {
        home: 'Home',
        search: 'Search',
        publish: 'Publish',
        msg: 'Message',
        me: 'Me',
      },
      tab1: {
        btnText: 'EN',
        modalTitle: 'Alert',
        modalBody: 'Are you sure you want to switch language?',
        cancel: 'Cancel',
        confirm: 'OK',
        searchPlaceholder: 'Click to Search',
        requestTitle: 'Request',
        helpTitle: 'Help',
        noEvent: 'No requests yet',
        noHelp: 'No help events yet',
        more: 'More',
        unknownDistance: 'Unknown distance',
      },
      tab2: {
        title: 'Search',
        searchPlaceholder: 'Click to Search',
        noResults: 'No results found',
        filterAll: 'All',
        filterRequest: 'Request',
        filterHelp: 'Help',
        unknownDistance: 'Unknown distance',
        loadFailed: 'Tab2 load failed',
      },
      tab3: {
        title: 'Messages',
        loginRequired: 'Hello! Please Login',
        loginRequiredSub: 'Welcome to HelpMe',
        loginHint: 'Login to view messages',
        loginBtn: 'Login Now',
        registerBtn: 'Register',
        notification: 'Notification',
        systemNotification: 'System Notification',
        noNewNotification: 'No new notifications',
        noMessage: 'No messages',
        loginToast: 'Please login or register',
        loadRoomsFailed: 'Failed to load chat list',
        unknownUser: 'User',
      },
      tab4: {
        title: 'Profile',
        welcome: 'Welcome to HelpMe',
        loginHint: 'Login to view your profile',
        loginBtn: 'Login Now',
        registerBtn: 'Register',
        locationNotSet: 'Location not set',
        introDefault: 'Your introduction is waiting to be explored!',
        buyerRating: 'Buyer Rating',
        serviceRating: 'Service Rating',
        orderCount: 'Orders',
        editProfile: 'Edit Profile',
        logout: 'Logout',
        follow: 'Follow',
        favorite: 'Favorite',
        view: 'Views',
        tabPublished: 'Published',
        tabInProgress: 'In Progress',
        tabCompleted: 'Completed',
        tabReview: 'Reviews',
        publishTime: 'Published',
        delete: 'Delete',
        edit: 'Edit',
        viewDetails: 'Details',
        review: 'Review',
        deleting: 'Deleting...',
        noTasks: 'No tasks yet',
        deleteConfirmTitle: 'Confirm Delete',
        deleteConfirmMsg: 'This action cannot be undone. Continue?',
        cancel: 'Cancel',
        confirm: 'Confirm',
        editEventTitle: 'Edit Event',
        close: 'Close',
        titleLabel: 'Title',
        titlePlaceholder: 'Brief description (e.g., Computer Repair)',
        typeLabel: 'Type',
        typePlaceholder: 'Select event type',
        typeRequest: 'Request',
        typeHelp: 'Help',
        categoryLabel: 'Category',
        categoryPlaceholder: 'e.g., Computer Repair',
        locationLabel: 'Location',
        locationPlaceholder: 'Detailed address',
        priceLabel: 'Price (¥)',
        pricePlaceholder: '0 for free',
        detailsLabel: 'Details',
        detailsPlaceholder: 'Describe your needs or services',
        editPhotoLabel: 'Edit Photos (Optional)',
        uploadPhoto: 'Click to upload',
        uploadHint: 'Max 5 photos, JPG/PNG supported',
        save: 'Save',
        saving: 'Saving...',
        editProfileTitle: 'Edit Profile',
        changeAvatar: 'Change Avatar',
        uploadAvatar: 'Upload Avatar',
        avatarHint: 'JPG/PNG, max 5MB',
        userNameLabel: 'Username',
        userNamePlaceholder: 'Enter username (2-20 chars)',
        realNameLabel: 'Real Name',
        realNamePlaceholder: 'Enter real name (2-20 chars)',
        idCardLabel: 'ID Card Number',
        idCardPlaceholder: 'Enter 18-digit ID number',
        locationLabelProfile: 'Location',
        locationPlaceholderProfile: 'e.g., Liuzhou, Guangxi',
        birthDateLabel: 'Birth Date',
        introLabel: 'Bio',
        introPlaceholder: 'Introduce yourself (optional, max 200 chars)',
        requiredHint: '* Required fields',
        verified: 'Verified',
        rejected: 'Rejected',
        pending: 'Pending',
        notVerified: 'Not Verified',
        statusPublished: 'Published',
        statusInProgress: 'In Progress',
        statusCompleted: 'Completed',
        statusPendingReview: 'Pending Review',
        statusUnknown: 'Unknown',
        logoutSuccess: 'Logged out successfully',
        deleteSuccess: 'Deleted successfully',
        saveSuccess: 'Saved successfully',
        notLoggedIn: 'Please login first',
        loginExpired: 'Login expired, please login again',
        networkError: 'Network error, please try again',
        pleaseCompleteRequired: 'Please complete required fields',
        titleRequired: 'Title is required',
        categoryRequired: 'Category is required',
        locationRequired: 'Location is required',
        detailsRequired: 'Details are required',
        priceInvalid: 'Price must be between 0 and 1,000,000',
        all: 'All',
        pendingConfirm: 'Pending',
        confirmComplete: 'Complete',
        goReview: 'Review',
        viewReview: 'View Review',
        orderDetail: 'Order Detail',
        eventDetail: 'Event Detail',
        eventNo: 'Event #:',
        noEvents: 'No events',
        noOrders: 'No orders',
        eventLoading: 'Loading events...',
        orderLoading: 'Loading orders...',
        linkedOrderBlockDelete: 'Linked order, cannot delete',
        myEvents: 'My Events',
        myOrders: 'My Orders',
        orderInfo: 'Order Info',
        orderId: 'Order ID:',
        orderTime: 'Order Time:',
        buyer: 'Buyer',
        seller: 'Seller',
        orderStatus: 'Order Status:',
        dealPrice: 'Deal Price:',
        eventInfoOnOrder: 'Event Info at Order Time',
        categoryColon: 'Category:',
        uncategorized: 'Uncategorized',
        locationColon: 'Location:',
        notFilled: 'Not filled',
        priceColon: 'Price:',
        descriptionColon: 'Description:',
        eventPhotos: 'Event Photos:',
        stopEditOrderInProgress: 'Cannot edit event while order is in progress or pending review',
        orderReviewTitle: 'Order Review',
        rating: 'Rating',
        fiveStar: '5 Stars',
        fourStar: '4 Stars',
        threeStar: '3 Stars',
        twoStar: '2 Stars',
        oneStar: '1 Star',
        reviewContent: 'Review Content',
        reviewPlaceholder: 'Write your review',
        submitReview: 'Submit Review',
        reviewDetailTitle: 'Review Details',
        loading: 'Loading...',
        noReviews: 'No reviews',
        reviewSubmitted: 'Review submitted',
        alreadyReviewed: 'You have already reviewed this order, waiting for the other party',
        confirmOrder: 'Confirm Order',
        cancelOrder: 'Cancel Order',
        confirmCancelMsg: 'Are you sure you want to cancel this order? This action cannot be undone.',
        confirmCancel: 'Confirm Cancel',
        orderConfirmed: 'Order confirmed',
        orderCompleted: 'Order completed',
        orderCancelled: 'Order cancelled',
        alertCancel: 'Cancel',
        alertConfirm: 'Confirm',
      },
      shared: {
        search: {
          placeholder: 'Enter your needs...',
          priceRange: 'Price Range',
          locationFilter: 'Location',
          reset: 'Reset',
          noResults: 'No matching results',
          priceFilterTitle: 'Price Filter',
          close: 'Close',
          minPrice: 'Min',
          maxPrice: 'Max',
          locationFilterTitle: 'Enter Location Keyword',
          locationLabel: 'Location Keyword (Match Address)',
          locationPlaceholder: 'e.g., Campus, 001...',
          request: 'Request',
          help: 'Help',
        },
        eventCard: {
          eventImage: 'Event Image',
          userAvatar: 'User Avatar',
        },
        eventsPanel: {
          loading: 'Loading events...',
          notFilled: 'No location',
          eventNo: 'Event #:',
          details: 'Details',
          editForbidden: 'Order in progress, edit forbidden',
          deleteForbidden: 'Linked order exists, delete forbidden',
          edit: 'Edit',
          deleting: 'Deleting...',
          delete: 'Delete',
          noEvents: 'No events',
        },
        ordersPanel: {
          all: 'All',
          pending: 'Pending',
          inProgress: 'In Progress',
          pendingReview: 'To Review',
          completed: 'Completed',
          buyer: 'Buyer',
          seller: 'Seller',
          orderNo: 'Order #:',
          orderDetail: 'Order Detail',
          eventDetail: 'Event Detail',
          cancelOrder: 'Cancel Order',
          confirmOrder: 'Confirm Order',
          confirmComplete: 'Confirm Complete',
          goReview: 'Review',
          waitReview: 'Reviewed, waiting',
          viewReview: 'View Review',
          noOrders: 'No orders',
          loading: 'Loading orders...',
        },
        profileCard: {
          realName: 'Name:',
          intro: 'Bio:',
          birthDate: 'Birth Date:',
        },
      },
      tab5: {
        header: 'Publish Service',
        hero: 'Helping each other',
        reqTitle: 'Request',
        reqDesc: 'Post when in need',
        helpTitle: 'Offer',
        helpDesc: 'Post to help others',
        authTitle: 'Verification',
        authDesc: 'Full-time Part-time Merchant',
        closeHint: 'Close and return',
        form: {
          reqHeader: 'Post Request',
          helpHeader: 'Post Offer',
          authHeader: 'Verification',
          title: 'Title',
          category: 'Category',
          location: 'Location',
          price: 'Price (¥)',
          details: 'Details',
          uploadPhoto: 'Upload Photos (Optional)',
          uploadHint: 'Max 5 photos, JPG/PNG',
          uploadIdCard: 'ID Card Photos',
          uploadCert: 'Certificates (Max 3)',
          realName: 'Real Name',
          phone: 'Phone Number',
          idCard: 'ID Card Number',
          area: 'Area',
          role: 'Role Type',
          intro: 'Bio',
          cancel: 'Cancel',
          submit: 'Submit',
          submitReq: 'Submit Request',
          submitHelp: 'Post Offer',
          submitAuth: 'Submit Verification',
        },
        placeholder: {
          reqTitle: 'Briefly describe your need',
          reqCat: 'e.g. Computer Repair',
          reqLoc: 'Detailed Address',
          reqPrice: '0 for free',
          reqDetail: 'Describe difficulty, time, urgency...',
          helpTitle: 'e.g. Computer Repair Service',
          helpCat: 'e.g. Repair',
          helpLoc: 'e.g. XX Community',
          helpPrice: 'e.g. 59.99',
          helpDetail: 'Describe what you can offer...',
          realName: 'Match ID Card',
          phone: '11 digits CN Mobile',
          idCard: '18 digits ID Number',
          area: 'e.g. XX Community',
          intro: 'Briefly introduce your experience',
        },
        toast: {
          pleaseComplete: 'Please complete required fields before submitting',
          loginFirst: 'Please login before publishing',
          publishSuccess: 'Published successfully',
          authSuccess: 'Verification submitted, pending review',
        },
        validation: {
          titleRequired: 'Title is required',
          categoryRequired: 'Category is required',
          locationRequired: 'Location is required',
          detailsRequired: 'Details are required',
          priceInvalid: 'Price is required (0 ~ 1,000,000)',
          serviceAreaRequired: 'Service area is required',
          serviceDetailsRequired: 'Service details are required',
          servicePriceInvalid: 'Service price is required (0 ~ 1,000,000)',
          realNameRequired: 'Real name is required',
          idCardInvalid: 'ID number is required (18 digits, last may be X)',
          areaRequired: 'Area is required',
          roleRequired: 'Role type is required (1/2/3 only)',
          idCardPhotoRequired: 'Please upload ID card photos (front and back)',
          certPhotoRequired: 'Please upload certificate photos',
        },
      },
      login: {
        title: 'Login',
        close: 'Close',
        welcome: 'Welcome Back',
        hint: 'Enter your phone number and verification code',
        phone: 'Phone',
        phonePlaceholder: 'Enter phone number',
        code: 'Code',
        codePlaceholder: 'Enter code',
        sendCode: 'Send Code',
        login: 'Login',
        tip: 'Tip: Test phone is 1380000000X, code is 1234',
        invalidPhone: 'Please enter a valid 11-digit phone number',
        verifyFail: 'Unable to verify phone, please try again later',
        notRegistered: 'This phone number is not registered',
        codeSent: 'Code sent, test code is 1234',
        incomplete: 'Please complete phone and code',
        loginSuccess: 'Login successful, {name}, welcome!',
        loginFailFormat: 'Login failed: unexpected server response',
        serverUnreachable: 'Cannot connect to server (check if backend is running)',
      },
      register: {
        title: 'Register',
        close: 'Close',
        step1Title: 'Verify Phone',
        step1Hint: 'Enter your phone number and get verification code',
        phone: 'Phone',
        phonePlaceholder: 'Enter phone number',
        code: 'Code',
        codePlaceholder: 'Enter code',
        sendCode: 'Send Code',
        next: 'Next',
        tip: 'Tip: Test code is 1234',
        step2Title: 'Complete Profile',
        step2Hint: 'Fill in your basic info',
        changeAvatar: 'Change Avatar',
        uploadAvatar: 'Upload Avatar',
        deleteAvatar: 'Delete',
        avatarHint: 'Default avatar if not uploaded, supports jpg/png, max 5MB',
        userName: 'Username *',
        realName: 'Real Name *',
        idCard: 'ID Number *',
        location: 'Location *',
        locationPlaceholder: 'Select location',
        birthDate: 'Birth Date *',
        intro: 'Bio',
        introPlaceholder: 'Introduce yourself (optional, max 200 chars)',
        prev: 'Previous',
        registering: 'Registering...',
        submit: 'Complete Registration',
        requiredHint: '* Required fields',
        phoneRequired: 'Phone number is required',
        codeRequired: 'Verification code is required',
        invalidCode: 'Invalid verification code',
        phoneRegistered: 'This phone number is already registered',
        pleaseComplete: 'Please complete all required fields',
        registerSuccess: 'Registration successful',
        registerFail: 'Registration failed',
        registerFailFormat: 'Registration failed: unexpected server response',
        serverUnreachable: 'Cannot connect to server (check if backend is running)',
        usernameExists: 'Username already exists',
      },
      particular: {
        back: 'Back',
        home: 'Home',
        buyerRating: 'Buyer Rating:',
        serviceRating: 'Service Rating:',
        serviceCount: 'Orders:',
        registerTime: 'Joined:',
        location: 'Location:',
        time: 'Time:',
        price: 'Price:',
        noImage: 'No image',
        favorite: 'Favorite',
        placeOrder: 'Order',
        cannotOrder: 'Cannot Order',
        edit: 'Edit',
        chat: 'Chat',
        editEvent: 'Edit Event',
        close: 'Close',
        titleRequired: 'Title *',
        typeRequired: 'Type *',
        request: 'Request',
        help: 'Help',
        categoryRequired: 'Category *',
        locationRequired: 'Location *',
        priceLabel: 'Price (¥)',
        detailsRequired: 'Details *',
        saving: 'Saving...',
        save: 'Save Changes',
        orderForm: 'Order Form',
        addressRequired: 'Address *',
        extraInfo: 'Additional Info',
        submitting: 'Submitting...',
        confirmOrder: 'Confirm Order',
        editSuccess: 'Changes saved',
        orderSuccess: 'Order placed, waiting for seller confirmation',
        networkError: 'Network error, please try again',
        loginFirst: 'Please login first',
      },
      search: {
        placeholder: 'Enter your needs',
        back: 'Back',
        search: 'Search',
        aiAssist: 'AI Assist',
      },
      chatDetail: {
        title: 'Chat',
        userAvatar: 'User Avatar',
        me: 'Me',
        other: 'Partner',
        inputPlaceholder: 'Type a message...',
        send: 'Send',
        justNow: 'Just now',
        systemNotification: 'System Notification',
        connected: 'Connected!',
      },
      userParticular: {
        title: 'User Profile',
        home: 'Home',
        address: 'Address:',
        buyerRating: 'Buyer Rating:',
        serviceRating: 'Service Rating:',
        serviceCount: 'Orders:',
        intro: 'Bio:',
        noIntro: 'No introduction',
        edit: 'Edit',
        follow: 'Follow',
        publishedEvents: 'Published Events',
        review: 'Reviews',
        historyEvents: 'History',
        noActiveEvents: 'No active events',
        noReviews: 'No reviews',
        noHistory: 'No activity',
        loginFirst: 'Please login first',
        cannotChatSelf: 'Cannot chat with yourself',
        request: 'Request',
        help: 'Help',
        enthusiast: 'Enthusiast',
        expert: 'Expert',
        normal: 'User',
        published: 'Published',
        inProgress: 'In Progress',
        completed: 'Completed',
        pendingReview: 'Pending Review',
        activity: 'Activity',
        noDescription: 'No description',
      },
      locationPicker: {
        title: 'Select Location',
        confirmLocation: 'Confirm Location',
        searchPlaceholder: 'Search places',
        search: 'Search',
        nearbyRecommend: 'Nearby',
        km: 'km',
        m: 'm',
        nearby: 'Nearby',
        loading: 'Loading...',
        noResult: 'No places found, try another keyword',
        searchResult: 'Results',
      },
      common: {
        save: 'Save',
        cancel: 'Cancel',
        confirm: 'Confirm',
        close: 'Close',
        delete: 'Delete',
        edit: 'Edit',
        loading: 'Loading...',
        noData: 'No data',
        networkError: 'Network error, please try again',
        loginExpired: 'Login expired, please login again',
        loginSuccessNoToken: 'Login successful but server did not return a token',
        loginFailedFormat: 'Login failed: unexpected server response',
        serverUnreachable: 'Cannot connect to server (check if backend is running)',
        pleaseComplete: 'Please fill in all required fields',
      },
    },
  };

  constructor() {}

  getTranslations(lang: 'zh' | 'en') {
    return this.translations[lang];
  }

  toggleLanguage() {
    const newLang = this.currentLangSubject.value === 'zh' ? 'en' : 'zh';
    this.currentLangSubject.next(newLang);
  }

  getCurrentLang() {
    return this.currentLangSubject.value;
  }
}
